import org.gradle.kotlin.dsl.the
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnLockMismatchReport
import org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnPlugin
import org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnRootExtension

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.ktlint)
    alias(libs.plugins.maven.publish)
}

group = "com.quarkdown.bibliographer"
version = file("version.txt").readText().trim()

// KGP strips directory npm dependencies from published metadata, so remote
// publications must resolve the binding from a public tarball URL instead:
// the release workflow attaches the packed binding to the GitHub release and
// passes both properties. Local builds default to the vendored directory.
val hayagrivaWasmFromRelease = providers.gradleProperty("hayagrivaWasmFromRelease").isPresent
val hayagrivaWasmTarballUrl: String by lazy {
    checkNotNull(providers.gradleProperty("hayagrivaWasmTarballUrl").orNull) {
        "-PhayagrivaWasmFromRelease also requires -PhayagrivaWasmTarballUrl"
    }
}

// Embeds the StyleCatalog styles, vendored in styles/, as JVM resources, so
// name resolution needs no styles dependency on the consumer's classpath.
// The wasm binding embeds the same files (hayagriva-wasm/build.rs), keeping
// the catalog byte-identical across platforms.
interface ExtractCatalogStylesServices {
    @get:Inject val fileSystem: FileSystemOperations
}

val extractCatalogStyles: TaskProvider<*> =
    tasks.register("extractCatalogStyles") {
        val catalogFile = file("src/commonMain/kotlin/com/quarkdown/bibliographer/StyleCatalog.kt")
        val vendoredStyles = file("styles")
        val outputDir = layout.buildDirectory.dir("generated/catalog-styles")
        val stylesDir = "com/quarkdown/bibliographer/styles"
        val services = objects.newInstance<ExtractCatalogStylesServices>()

        inputs.dir(vendoredStyles)
        inputs.file(catalogFile)
        outputs.dir(outputDir)

        doLast {
            val outDir = outputDir.get().asFile
            outDir.deleteRecursively()

            val names =
                Regex("^\\s*\"([a-z0-9-]+)\",$", RegexOption.MULTILINE)
                    .findAll(catalogFile.readText())
                    .map { it.groupValues[1] }
                    .toSet()
            check(names.isNotEmpty()) { "No style names parsed from ${catalogFile.name}" }

            // StyleCatalog.kt and styles/ must stay in lockstep, in both directions.
            val vendored =
                vendoredStyles
                    .listFiles { file -> file.extension == "csl" }
                    .orEmpty()
                    .map { it.nameWithoutExtension }
                    .toSet()
            val missing = names - vendored
            check(missing.isEmpty()) { "Catalog styles missing from styles/: ${missing.joinToString()}" }
            val unlisted = vendored - names
            check(unlisted.isEmpty()) { "styles/ contains styles not in StyleCatalog: ${unlisted.joinToString()}" }

            services.fileSystem.copy {
                from(vendoredStyles)
                into(outDir.resolve(stylesDir))
                include("*.csl")
            }
        }
    }

kotlin {
    explicitApi()
    jvmToolchain(11)

    jvm()

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        nodejs()
    }

    sourceSets {
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        jvmMain {
            resources.srcDir(extractCatalogStyles)
            dependencies {
                api(libs.citeproc.java)
                runtimeOnly(libs.csl.locales)
            }
        }
        jvmTest.dependencies {
            implementation(libs.csl.styles)
        }
        wasmJsMain.dependencies {
            // Vendored, npm-shaped hayagriva-wasm package (see src/wasmJsMain/npm/hayagriva-wasm/,
            // regenerated by hayagriva-wasm/regenerate.sh). Local builds resolve the directory;
            // release builds resolve the same package from its GitHub release tarball.
            implementation(
                if (hayagrivaWasmFromRelease) {
                    npm("hayagriva-wasm", hayagrivaWasmTarballUrl)
                } else {
                    npm("hayagriva-wasm", projectDir.resolve("src/wasmJsMain/npm/hayagriva-wasm"))
                },
            )
        }
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

// Remote publishing with the directory dependency would ship a consumer-broken
// wasm artifact (the dependency is absent from the published metadata).
tasks.withType<PublishToMavenRepository>().configureEach {
    // Captured as a local value (not a reference into the build script itself) so the
    // task action stays configuration-cache-compatible.
    val fromRelease = hayagrivaWasmFromRelease
    doFirst {
        if (!fromRelease) {
            error(
                "The wasmJs 'hayagriva-wasm' npm dependency is a local directory dependency, " +
                    "which is stripped from published metadata and would break consumers. " +
                    "Publish with -PhayagrivaWasmFromRelease=true so consumers resolve the " +
                    "GitHub release tarball instead.",
            )
        }
    }
}

// The committed yarn.lock matches the directory dependency; in release mode the
// coordinate legitimately differs, so the lock mismatch is reported, not fatal.
if (hayagrivaWasmFromRelease) {
    plugins.withType<WasmYarnPlugin> {
        the<WasmYarnRootExtension>().apply {
            yarnLockMismatchReportProperty.set(YarnLockMismatchReport.WARNING)
            reportNewYarnLockProperty.set(false)
        }
    }
}

ktlint {
    version.set(libs.versions.ktlint.engine)
}

mavenPublishing {
    coordinates(group.toString(), "bibliographer", version.toString())

    publishToMavenCentral()

    if (providers.gradleProperty("signingInMemoryKey").isPresent) {
        signAllPublications()
    }

    pom {
        name.set("kotlin-bibliographer")
        description.set(
            "Kotlin Multiplatform bridge from CSL (Citation Style Language) processors " +
                "to a platform-agnostic bibliography token domain.",
        )
        url.set("https://github.com/quarkdown-labs/kotlin-bibliographer/")
        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                id.set("iamgio")
                name.set("Giorgio Garofalo")
                url.set("https://github.com/iamgio")
            }
        }
        scm {
            url.set("https://github.com/quarkdown-labs/kotlin-bibliographer/")
            connection.set("scm:git:git://github.com/quarkdown-labs/kotlin-bibliographer.git")
            developerConnection.set("scm:git:ssh://git@github.com/quarkdown-labs/kotlin-bibliographer.git")
        }
    }
}
