import org.gradle.kotlin.dsl.the
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnLockMismatchReport
import org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnPlugin
import org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnRootExtension

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.ktlint)
    alias(libs.plugins.maven.publish)
}

group = "com.quarkdown.bibliographer"
version = file("version.txt").readText().trim()

// The vendored hayagriva binding's version, kept equal to the wrapper crate's
// version by regenerate.sh.
val hayagrivaWasmVersion =
    Regex("\"version\": \"([^\"]+)\"")
        .find(file("src/wasmJsMain/npm/hayagriva-wasm/package.json").readText())!!
        .groupValues[1]

// KGP strips directory npm dependencies from published metadata, so remote
// publications must resolve the binding from a public tarball URL instead.
// The release workflow passes -PhayagrivaWasmFromRelease=true; local builds
// default to the vendored directory.
val hayagrivaWasmFromRelease = providers.gradleProperty("hayagrivaWasmFromRelease").isPresent
val hayagrivaWasmTarballUrl =
    providers.gradleProperty("hayagrivaWasmTarballUrl").orNull
        ?: (
            "https://github.com/quarkdown-labs/kotlin-bibliographer/releases/download/" +
                "hayagriva-wasm-v$hayagrivaWasmVersion/hayagriva-wasm-$hayagrivaWasmVersion.tgz"
        )

kotlin {
    explicitApi()
    jvmToolchain(11)

    jvm()

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        nodejs()
    }

    sourceSets {
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        jvmMain.dependencies {
            api(libs.citeproc.java)
            runtimeOnly(libs.csl.locales)
        }
        jvmTest.dependencies {
            implementation(libs.csl.styles)
        }
        wasmJsMain.dependencies {
            // Vendored, npm-shaped hayagriva-wasm package (see src/wasmJsMain/npm/hayagriva-wasm/,
            // regenerated by hayagriva-wasm/regenerate.sh). Local builds resolve the directory;
            // release builds resolve the same package from its GitHub release tarball.
            implementation(
                if (hayagrivaWasmFromRelease) {
                    npm("hayagriva-wasm", hayagrivaWasmTarballUrl)
                } else {
                    npm("hayagriva-wasm", projectDir.resolve("src/wasmJsMain/npm/hayagriva-wasm"))
                },
            )
        }
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

// Remote publishing with the directory dependency would ship a consumer-broken
// wasm artifact (the dependency is absent from the published metadata).
tasks.withType<PublishToMavenRepository>().configureEach {
    // Captured as a local value (not a reference into the build script itself) so the
    // task action stays configuration-cache-compatible.
    val fromRelease = hayagrivaWasmFromRelease
    doFirst {
        if (!fromRelease) {
            error(
                "The wasmJs 'hayagriva-wasm' npm dependency is a local directory dependency, " +
                    "which is stripped from published metadata and would break consumers. " +
                    "Publish with -PhayagrivaWasmFromRelease=true so consumers resolve the " +
                    "GitHub release tarball instead.",
            )
        }
    }
}

// The committed yarn.lock matches the directory dependency; in release mode the
// coordinate legitimately differs, so the lock mismatch is reported, not fatal.
if (hayagrivaWasmFromRelease) {
    plugins.withType<WasmYarnPlugin> {
        the<WasmYarnRootExtension>().apply {
            yarnLockMismatchReportProperty.set(YarnLockMismatchReport.WARNING)
            reportNewYarnLockProperty.set(false)
        }
    }
}

ktlint {
    version.set(libs.versions.ktlint.engine)
}

mavenPublishing {
    coordinates(group.toString(), "bibliographer", version.toString())

    publishToMavenCentral()

    if (providers.gradleProperty("signingInMemoryKey").isPresent) {
        signAllPublications()
    }

    pom {
        name.set("kotlin-bibliographer")
        description.set(
            "Kotlin Multiplatform bridge from CSL (Citation Style Language) processors " +
                "to a platform-agnostic bibliography token domain.",
        )
        url.set("https://github.com/quarkdown-labs/kotlin-bibliographer/")
        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                id.set("iamgio")
                name.set("Giorgio Garofalo")
                url.set("https://github.com/iamgio")
            }
        }
        scm {
            url.set("https://github.com/quarkdown-labs/kotlin-bibliographer/")
            connection.set("scm:git:git://github.com/quarkdown-labs/kotlin-bibliographer.git")
            developerConnection.set("scm:git:ssh://git@github.com/quarkdown-labs/kotlin-bibliographer.git")
        }
    }
}
