plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.ktlint)
    alias(libs.plugins.maven.publish)
}

group = "com.quarkdown.bibliographer"
version = file("version.txt").readText().trim()

kotlin {
    explicitApi()
    jvmToolchain(11)

    jvm()

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        nodejs()
    }

    sourceSets {
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        jvmMain.dependencies {
            api(libs.citeproc.java)
            runtimeOnly(libs.csl.locales)
        }
        jvmTest.dependencies {
            implementation(libs.csl.styles)
        }
        wasmJsMain.dependencies {
            // Vendored, npm-shaped hayagriva-wasm package (see src/wasmJsMain/npm/hayagriva-wasm/,
            // regenerated by hayagriva-wasm/regenerate.sh).
            // Resolved as a directory dependency so Gradle never invokes Rust/npm registry;
            // flipped to a packed tarball URL before a Maven Central release.
            implementation(npm("hayagriva-wasm", projectDir.resolve("src/wasmJsMain/npm/hayagriva-wasm")))
        }
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

// The vendored hayagriva binding is wired as a directory npm dependency, which KGP
// strips from published metadata (consumers would get a runtime-broken artifact).
// Block remote publishing until the release flips the coordinate to a tarball URL.
val hayagrivaNpmDependencyIsLocal = true

tasks.withType<PublishToMavenRepository>().configureEach {
    // Captured as a local value (not a reference into the build script itself) so the
    // task action stays configuration-cache-compatible.
    val isLocalDependency = hayagrivaNpmDependencyIsLocal
    doFirst {
        if (isLocalDependency) {
            error(
                "The wasmJs 'hayagriva-wasm' npm dependency is a local directory dependency, " +
                    "which is stripped from published metadata and would break consumers. " +
                    "Flip it to the release tarball URL before publishing remotely.",
            )
        }
    }
}

ktlint {
    version.set(libs.versions.ktlint.engine)
}

mavenPublishing {
    coordinates(group.toString(), "bibliographer", version.toString())

    publishToMavenCentral()

    if (providers.gradleProperty("signingInMemoryKey").isPresent) {
        signAllPublications()
    }

    pom {
        name.set("kotlin-bibliographer")
        description.set(
            "Kotlin Multiplatform bridge from CSL (Citation Style Language) processors " +
                "to a platform-agnostic bibliography token domain.",
        )
        url.set("https://github.com/quarkdown-labs/kotlin-bibliographer/")
        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                id.set("iamgio")
                name.set("Giorgio Garofalo")
                url.set("https://github.com/iamgio")
            }
        }
        scm {
            url.set("https://github.com/quarkdown-labs/kotlin-bibliographer/")
            connection.set("scm:git:git://github.com/quarkdown-labs/kotlin-bibliographer.git")
            developerConnection.set("scm:git:ssh://git@github.com/quarkdown-labs/kotlin-bibliographer.git")
        }
    }
}
