//! The wrapper's platform-independent core: parsing a bibliography source and
//! a CSL style, then rendering citations and bibliographies as the token JSON
//! defined in [`crate::tokens`]. The wasm-bindgen exports are a thin shell
//! around [`Bibliographer`], so everything here is testable with plain
//! `cargo test`.

use hayagriva::citationberg::json::Item as CslJsonItem;
use hayagriva::citationberg::{IndependentStyle, Locale, LocaleCode, LocaleFile};
use hayagriva::io::from_biblatex_str;
use hayagriva::{
    BibliographyDriver, BibliographyRequest, CitationItem, CitationRequest, Entry, Rendered,
};
use std::sync::OnceLock;

use crate::tokens;

// `static LOCALE_XML: &[&str]` — one `include_str!` per `locales/*.xml`,
// generated by `build.rs` so the list never needs manual maintenance.
include!(concat!(env!("OUT_DIR"), "/locale_includes.rs"));

/// The CSL locale definitions a style falls back to for its localized terms,
/// parsed once on first use.
///
/// Styles that reference terms from a locale this crate failed to parse
/// simply fall back to the style's own definitions, exactly as they would
/// for a locale that was never bundled, so unparseable files are skipped
/// rather than turned into a hard failure at first render.
fn locales() -> &'static [Locale] {
    static LOCALES: OnceLock<Vec<Locale>> = OnceLock::new();
    LOCALES.get_or_init(|| {
        LOCALE_XML
            .iter()
            .filter_map(|xml| LocaleFile::from_xml(xml).ok())
            .map(Into::into)
            .collect()
    })
}

/// Which bibliography source format is being parsed.
pub enum SourceFormat {
    Bibtex,
    CslJson,
}

impl SourceFormat {
    /// Parse a format identifier as used on the Kotlin/JS side of the
    /// wrapper. Accepts exactly `"bibtex"` and `"csl-json"`.
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "bibtex" => Some(Self::Bibtex),
            "csl-json" => Some(Self::CslJson),
            _ => None,
        }
    }
}

/// The parsed bibliography, in whichever native representation its source
/// format produces.
///
/// hayagriva 0.10.1 has no conversion from `citationberg::json::Item`
/// (csl-json's item type) to hayagriva's own `Entry` — the two are
/// independent implementations of hayagriva's internal (crate-private)
/// `EntryLike` trait, both accepted directly by the generic rendering
/// pipeline (`CitationItem`, `CitationRequest`, `BibliographyDriver<T>`).
/// So rather than converting csl-json into `Entry` (which would require
/// hand-rolling a `Kind`-to-`EntryType` taxonomy mapping hayagriva itself
/// doesn't provide, with all its lossy edge cases),
/// each source format keeps its own native item type here, and
/// [`Bibliographer::render`] dispatches on this enum with one concrete driver
/// set-up per branch.
enum Entries {
    Bibliography(Vec<Entry>),
    CslJson(Vec<CslJsonItem>),
}

pub struct Bibliographer {
    style: IndependentStyle,
    entries: Entries,
    /// The citation key of every entry, in source order — index `i` here is
    /// index `i` in [`Entries`], which is what [`Self::resolve`] relies on to
    /// look up entries without knowing which source format is in play.
    /// Computed once at construction; entries never change afterwards.
    keys: Vec<String>,
    locale: Option<LocaleCode>,
}

impl Bibliographer {
    pub fn new(
        style_xml: &str,
        source: &str,
        format: SourceFormat,
        locale: Option<&str>,
    ) -> Result<Self, String> {
        let style = IndependentStyle::from_xml(style_xml)
            .map_err(|e| format!("Invalid CSL style: {e}"))?;
        let entries = match format {
            SourceFormat::Bibtex => {
                let parsed: Vec<Entry> = from_biblatex_str(source)
                    .map_err(|errors| {
                        let details: Vec<String> =
                            errors.iter().map(ToString::to_string).collect();
                        format!("Invalid BibTeX source: {}", details.join("; "))
                    })?
                    .into_iter()
                    .collect();
                // biblatex::Bibliography::parse only recognizes `@`-prefixed
                // entries and silently ignores everything else (verified:
                // parsing "not bibtex {{{" returns `Ok` with zero entries,
                // not a `ParseError` — there is no top-level "this doesn't
                // look like BibTeX" check in biblatex 0.12.0). A source that
                // yields no citable entries is treated as invalid input here
                // so the wrapper still surfaces a descriptive error for
                // garbage input, per the fixed test semantics.
                if parsed.is_empty() {
                    return Err("Invalid BibTeX source: no entries found".to_string());
                }
                Entries::Bibliography(parsed)
            }
            SourceFormat::CslJson => {
                let parsed: Vec<CslJsonItem> = serde_json::from_str(source)
                    .map_err(|e| format!("Invalid CSL-JSON source: {e}"))?;
                if parsed.is_empty() {
                    return Err("Invalid CSL-JSON source: no entries found".to_string());
                }
                // CSL-JSON requires an `id` on every item, and hayagriva uses
                // it as the citation key. An item without one could neither be
                // cited nor matched to its bibliography entry, and letting it
                // through would desynchronize `citation_keys` from the rendered
                // bibliography, so it is rejected outright rather than silently
                // dropped.
                if let Some(position) = parsed.iter().position(|item| item.id().is_none()) {
                    return Err(format!(
                        "Invalid CSL-JSON source: item at index {position} has no \"id\""
                    ));
                }
                Entries::CslJson(parsed)
            }
        };
        let keys = match &entries {
            Entries::Bibliography(entries) => {
                entries.iter().map(|e| e.key().to_string()).collect()
            }
            // Items without an "id" were rejected above, so nothing is
            // filtered out here and the result stays index-aligned.
            Entries::CslJson(items) => {
                items.iter().filter_map(|i| i.id().map(|id| id.to_string())).collect()
            }
        };
        // citationberg::LocaleCode is a plain tuple struct (no `From<&str>`
        // impl in citationberg 0.7.0), so it is constructed directly.
        let locale = locale.map(|s| LocaleCode(s.to_string()));
        Ok(Self { style, entries, keys, locale })
    }

    /// The citation key of every entry, in source order.
    pub fn citation_keys(&self) -> &[String] {
        &self.keys
    }

    /// Renders the combined in-text citation for `keys`, as a JSON token
    /// array. Keys that name no entry are ignored; if none of them match,
    /// the render is empty and the empty string is returned.
    pub fn citation(&self, keys: &[String]) -> String {
        let cited = self.resolve(keys);
        if cited.is_empty() {
            return String::new();
        }
        let rendered = self.render(Some(&cited));
        // The visible request is appended last, after the hidden registration
        // one; see `render`.
        let Some(citation) = rendered.citations.last() else {
            return String::new();
        };
        let tokens = tokens::to_tokens(&citation.citation);
        if tokens.is_empty() {
            String::new()
        } else {
            serde_json::to_string(&tokens).expect("token JSON is always serializable")
        }
    }

    /// Renders every entry as a JSON array of
    /// `{"citationKey", "label", "content"}` objects, in the order the style's
    /// sorting rules dictate.
    pub fn bibliography(&self) -> String {
        let rendered = self.render(None);
        let items: Vec<serde_json::Value> = rendered
            .bibliography
            .iter()
            .flat_map(|bibliography| &bibliography.items)
            .map(|item| {
                serde_json::json!({
                    "citationKey": item.key,
                    // `first_field` is populated exactly for styles that ask
                    // for `second-field-align`, the numeric label of e.g.
                    // IEEE, which is presented separately from the content.
                    "label": item.first_field.as_ref().map(tokens::child_to_plain_text),
                    "content": tokens::to_tokens(&item.content),
                })
            })
            .collect();
        serde_json::to_string(&items).expect("bibliography JSON is always serializable")
    }

    /// Maps citation keys onto entry indices, dropping unknown ones.
    fn resolve(&self, keys: &[String]) -> Vec<usize> {
        keys.iter()
            .filter_map(|key| self.keys.iter().position(|candidate| candidate == key))
            .collect()
    }

    /// Runs the CSL machinery over the whole bibliography, optionally adding a
    /// visible citation for the entries at the given indices.
    ///
    /// Both [`Entries`] variants drive the same logic, but it has to be
    /// *expanded* per variant rather than called: hayagriva's `EntryLike`
    /// trait, which `BibliographyDriver`, `CitationRequest` and `CitationItem`
    /// are all generic over, is not exported, so no bound naming it can be
    /// written here and no generic function can be shared between the two item
    /// types. Hence the macro: it keeps one copy of the logic, and each
    /// expansion is type-checked against its own concrete item type. Only the
    /// driver set-up needs this treatment — [`Rendered`] is not generic, so
    /// everything downstream of it is ordinary shared code.
    ///
    /// The leading citation is hidden: it registers every entry with the driver
    /// without contributing anything to the rendered output. hayagriva numbers
    /// entries in the order it first encounters them across all citations, so
    /// without it the number an entry gets would depend on which keys a given
    /// [`Self::citation`] call happens to ask for — citing only the second entry
    /// would render `[1]`, contradicting its own `[2]` bibliography label.
    /// Registering them all makes numbering a property of the bibliography,
    /// matching the JVM backend, which hands citeproc every item the same way.
    ///
    /// Hidden items are excluded from the output and from ibid detection, but
    /// they do mark their entries as already seen, so `position="first"` tests
    /// false for every citation. That is an acceptable trade: this API renders
    /// each citation in isolation, with no document context, so
    /// first-versus-subsequent is not knowable either way, whereas citation
    /// numbers are — and must agree with the bibliography.
    fn render(&self, cited: Option<&[usize]>) -> Rendered {
        macro_rules! render_over {
            ($entries:expr) => {{
                let entries = $entries;
                let request = |items| {
                    CitationRequest::new(items, &self.style, self.locale.clone(), locales(), None)
                };
                let mut driver = BibliographyDriver::new();
                // `CitationItem` has private fields, so `hidden` is set on the
                // constructed item rather than through struct-update syntax.
                let registration = entries
                    .iter()
                    .map(|entry| {
                        let mut item = CitationItem::with_entry(entry);
                        item.hidden = true;
                        item
                    })
                    .collect();
                driver.citation(request(registration));
                if let Some(cited) = cited {
                    let items =
                        cited.iter().map(|&i| CitationItem::with_entry(&entries[i])).collect();
                    driver.citation(request(items));
                }
                driver.finish(self.bibliography_request())
            }};
        }

        match &self.entries {
            Entries::Bibliography(entries) => render_over!(entries),
            Entries::CslJson(entries) => render_over!(entries),
        }
    }

    /// The bibliography-wide half of a render request, shared by both branches
    /// of [`Self::render`] because it does not mention the entry type.
    fn bibliography_request(&self) -> BibliographyRequest<'_> {
        BibliographyRequest {
            style: &self.style,
            locale: self.locale.clone(),
            locale_files: locales(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const BIBTEX: &str = r#"
@article{einstein1905,
    author = {Einstein, Albert},
    title = {Zur Elektrodynamik bewegter K{\"o}rper},
    journal = {Annalen der Physik},
    year = {1905}
}
@book{hawking1988,
    author = {Hawking, Stephen},
    title = {A Brief History of Time},
    year = {1988}
}
"#;

    const CSL_JSON: &str = r#"[
        {"id": "einstein1905", "type": "article-journal",
         "title": "Zur Elektrodynamik bewegter Körper",
         "author": [{"family": "Einstein", "given": "Albert"}],
         "issued": {"date-parts": [[1905]]},
         "container-title": "Annalen der Physik"},
        {"id": "hawking1988", "type": "book", "title": "A Brief History of Time",
         "author": [{"family": "Hawking", "given": "Stephen"}],
         "issued": {"date-parts": [[1988]]}}
    ]"#;

    fn ieee() -> String { std::fs::read_to_string("tests/styles/ieee.csl").unwrap() }

    fn apa() -> String { std::fs::read_to_string("tests/styles/apa.csl").unwrap() }

    /// Flattens a token array back to its plain text, mirroring the Kotlin
    /// side's `toPlainText` so the fidelity assertions read like the JVM
    /// backend's.
    fn plain(tokens: &serde_json::Value) -> String {
        fn one(t: &serde_json::Value) -> String {
            match t["kind"].as_str().unwrap() {
                "text" => t["text"].as_str().unwrap().to_string(),
                "link" => one(&t["label"]),
                _ => one(&t["child"]),
            }
        }
        tokens.as_array().unwrap().iter().map(one).collect()
    }

    fn citation_tokens(b: &Bibliographer, keys: &[&str]) -> serde_json::Value {
        let keys: Vec<String> = keys.iter().map(|k| k.to_string()).collect();
        serde_json::from_str(&b.citation(&keys)).unwrap()
    }

    #[test]
    fn bibtex_keys_in_source_order() {
        let b = Bibliographer::new(&ieee(), BIBTEX, SourceFormat::Bibtex, None).unwrap();
        assert_eq!(b.citation_keys(), vec!["einstein1905", "hawking1988"]);
    }

    #[test]
    fn csl_json_keys_in_source_order() {
        let b = Bibliographer::new(&ieee(), CSL_JSON, SourceFormat::CslJson, None).unwrap();
        assert_eq!(b.citation_keys(), vec!["einstein1905", "hawking1988"]);
    }

    #[test]
    fn invalid_source_is_an_error() {
        assert!(Bibliographer::new(&ieee(), "not bibtex {{{", SourceFormat::Bibtex, None).is_err());
    }

    #[test]
    fn invalid_style_is_an_error() {
        assert!(Bibliographer::new("not xml", BIBTEX, SourceFormat::Bibtex, None).is_err());
    }

    #[test]
    fn csl_json_items_without_an_id_are_rejected() {
        let source = r#"[{"type": "book", "title": "Anonymous"}]"#;
        assert!(Bibliographer::new(&ieee(), source, SourceFormat::CslJson, None).is_err());
    }

    #[test]
    fn ieee_citations() {
        let b = Bibliographer::new(&ieee(), BIBTEX, SourceFormat::Bibtex, None).unwrap();
        assert_eq!(plain(&citation_tokens(&b, &["einstein1905"])), "[1]");
        assert_eq!(
            plain(&citation_tokens(&b, &["einstein1905", "hawking1988"])),
            "[1], [2]"
        );
    }

    /// Citation numbers are a property of the whole bibliography, not of the
    /// individual `citation` call: citing the second entry alone must still
    /// render `[2]`, matching both its bibliography label and the JVM
    /// (citeproc-java) backend, which pre-registers every entry.
    #[test]
    fn ieee_citation_numbers_are_global() {
        let b = Bibliographer::new(&ieee(), BIBTEX, SourceFormat::Bibtex, None).unwrap();
        assert_eq!(plain(&citation_tokens(&b, &["hawking1988"])), "[2]");
    }

    #[test]
    fn ieee_bibliography_has_labels_and_sorted_keys() {
        let b = Bibliographer::new(&ieee(), BIBTEX, SourceFormat::Bibtex, None).unwrap();
        let bib: serde_json::Value = serde_json::from_str(&b.bibliography()).unwrap();
        let items = bib.as_array().unwrap();
        assert_eq!(items[0]["citationKey"], "einstein1905");
        assert_eq!(items[0]["label"], "[1]");
        assert!(plain(&items[0]["content"]).contains("Einstein"));
        assert_eq!(items[1]["label"], "[2]");
    }

    #[test]
    fn apa_citation_and_unlabeled_sorted_bibliography() {
        let b = Bibliographer::new(&apa(), BIBTEX, SourceFormat::Bibtex, None).unwrap();
        assert_eq!(plain(&citation_tokens(&b, &["einstein1905"])), "(Einstein, 1905)");
        let bib: serde_json::Value = serde_json::from_str(&b.bibliography()).unwrap();
        for item in bib.as_array().unwrap() {
            assert!(item["label"].is_null());
        }
    }

    #[test]
    fn apa_italicizes_container_title() {
        let b = Bibliographer::new(&apa(), BIBTEX, SourceFormat::Bibtex, None).unwrap();
        let bib: serde_json::Value = serde_json::from_str(&b.bibliography()).unwrap();
        let einstein = &bib.as_array().unwrap()[0];
        let json = einstein["content"].to_string();
        assert!(json.contains("\"kind\":\"italic\""), "expected italic journal name: {json}");
    }

    #[test]
    fn csl_json_sources_render_like_bibtex_ones() {
        let b = Bibliographer::new(&ieee(), CSL_JSON, SourceFormat::CslJson, None).unwrap();
        assert_eq!(plain(&citation_tokens(&b, &["hawking1988"])), "[2]");
        let bib: serde_json::Value = serde_json::from_str(&b.bibliography()).unwrap();
        let items = bib.as_array().unwrap();
        assert_eq!(items[0]["citationKey"], "einstein1905");
        assert_eq!(items[0]["label"], "[1]");
        assert!(plain(&items[0]["content"]).contains("Einstein"));
    }

    #[test]
    fn empty_render_returns_empty_string() {
        let b = Bibliographer::new(&ieee(), BIBTEX, SourceFormat::Bibtex, None).unwrap();
        assert_eq!(b.citation(&[]), "");
    }

    #[test]
    fn unknown_keys_are_ignored_among_known_ones() {
        let b = Bibliographer::new(&ieee(), BIBTEX, SourceFormat::Bibtex, None).unwrap();
        assert_eq!(b.citation(&["unknown".to_string()]), "");
        assert_eq!(plain(&citation_tokens(&b, &["einstein1905", "unknown"])), "[1]");
    }

    /// Locale terms come from the embedded `locales-*.xml` files, so this also
    /// proves the build-time locale bundle is reachable and correctly indexed
    /// by locale code: IEEE renders the page label as `pp.` in English and as
    /// `S.` in German.
    #[test]
    fn locale_override_selects_localized_terms() {
        const PAGED: &str = r#"
@article{einstein1905,
    author = {Einstein, Albert},
    title = {Zur Elektrodynamik bewegter K{\"o}rper},
    journal = {Annalen der Physik},
    pages = {891--921},
    year = {1905}
}
"#;
        let render = |locale| {
            let b = Bibliographer::new(&ieee(), PAGED, SourceFormat::Bibtex, locale).unwrap();
            b.bibliography()
        };
        assert!(render(Some("en-US")).contains("pp."), "{}", render(Some("en-US")));
        assert!(render(Some("de-DE")).contains("S."), "{}", render(Some("de-DE")));
    }
}
